### ISSUE TITLE
Enhancement: Also provide a replace method on a node with children

### ISSUE THREAD

**Issue by Ehlster** [SwiftDocOrg/CommonMark#15]
Currently, there's no dedicated method to replace a node with another node.

One could already express a replacement with a combination of insert and remove, but I think it makes sense to also provide a wrapper around cmark's `cmark_node_replace()`. The same like we do for all the other operations on nodes.

I can provide a pull request once #11 is merged.

**Comment by mattt** [comment]
@Lukas-Stuehrk That sounds great! Given that there's already a `cmark` function that does this, it should be a straightforward addition (the hardest part may be getting the right argument order 😝).
